### ISSUE TITLE
Problem with data attributes not being recongized in alpha stage. Fabric keeps asking for "Data Attributes DC version 1.5.2) but there isn't one... wtf

### ISSUE THREAD

**Issue by TheShadyyOneYT** [BareMinimumStudios/data-attributes#19]
https://pastebin.com/17afMM9Q (pastebin of data attirbutes being funky + other mods)

https://imgur.com/a/jFxE9vy

**Comment by pokesmells** [comment]
It asks for 1.5.2 or higher...?

**Comment by TheShadyyOneYT** [comment]
bro im a dumbass, modrinth only shows 1 version, i was so confused my bad.

**Comment by TheShadyyOneYT** [comment]
thanks for the help
